use crate::content::lookup_rule;
use crate::ReportFinding;
use digger_evidence::{
    EngineVersion, EvidenceBundle, Finding, InputDescriptor, Location, ProvenanceInfo,
};
use digger_server::copilot::{generate_poc_scaffold, validate_poc, POC_DISCLAIMER};
use std::fmt::Write;

/// Render a ranked list of findings into deterministic Markdown.
///
/// All `writeln!(out, ...).unwrap()` calls below are safe: `out` is `&mut String`,
/// and `String`'s `fmt::Write` impl is infallible (never returns `Err`).
/// These cannot panic under any input condition.
pub fn render_report(findings: &[&ReportFinding]) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "# Security Analysis Report").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Generated by Digger v{} — deterministic analysis, no LLM.",
        env!("CARGO_PKG_VERSION")
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "---").unwrap();
    writeln!(out).unwrap();

    for (i, finding) in findings.iter().enumerate() {
        render_finding(&mut out, i + 1, finding);
    }

    out
}

fn render_finding(out: &mut String, index: usize, finding: &ReportFinding) {
    let content = lookup_rule(&finding.rule_id);

    // Title: "<VulnClass> in `<component>` — <one-line> (<file>:<lines>)"
    writeln!(
        out,
        "## {}. {} in `{}` — {} ({}:{})",
        index,
        content.display_name,
        finding.component,
        content
            .what_this_is
            .split('.')
            .next()
            .unwrap_or(&content.what_this_is),
        finding.file,
        finding.line_start,
    )
    .unwrap();
    writeln!(out).unwrap();

    // Summary
    writeln!(out, "### Summary").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "{}", content.what_this_is).unwrap();
    writeln!(out).unwrap();

    // Why it matters
    writeln!(out, "### Why it matters").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "{}", content.why_dangerous).unwrap();
    writeln!(out).unwrap();

    // Location & Code — with exact line range = actual excerpt span
    writeln!(out, "### Location & Code").unwrap();
    writeln!(out).unwrap();
    let line_end = if finding.evidence_lines.is_empty() {
        finding.line_end
    } else {
        finding.line_start + finding.evidence_lines.len() as u32 - 1
    };
    writeln!(
        out,
        "**File:** `{}` (lines {}–{})",
        finding.file, finding.line_start, line_end
    )
    .unwrap();
    writeln!(out).unwrap();
    if !finding.evidence_lines.is_empty() {
        writeln!(out, "```solidity").unwrap();
        for line in &finding.evidence_lines {
            writeln!(out, "{}", line).unwrap();
        }
        writeln!(out, "```").unwrap();
    } else {
        writeln!(out, "_No code excerpt available for this finding._").unwrap();
    }
    writeln!(out).unwrap();

    // Evidence path — render real evidence or honest "none" message
    writeln!(out, "### Evidence path").unwrap();
    writeln!(out).unwrap();
    if !finding.evidence_lines.is_empty() {
        // Describe WHAT the evidence shows, not restate finding metadata
        let first_line = finding
            .evidence_lines
            .first()
            .map(|s| s.trim())
            .unwrap_or("");
        writeln!(
            out,
            "The flagged code at `{}:{}` contains: `{}`",
            finding.file, finding.line_start, first_line,
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "_No execution-path evidence captured for this finding._"
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    // Severity & Confidence
    writeln!(out, "### Severity & Confidence").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "| Severity | Confidence |\n|----------|------------|\n| {} | {} |",
        finding.severity, finding.confidence
    )
    .unwrap();
    writeln!(out).unwrap();

    // Similar known issues (precedent citations)
    if !content.precedents.is_empty() {
        writeln!(out, "### Similar known issues").unwrap();
        writeln!(out).unwrap();
        for prec in &content.precedents {
            writeln!(
                out,
                "- **{}**: {} ({})",
                prec.name, prec.note, prec.reference,
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    } else {
        writeln!(out, "### Similar known issues").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "_No precedent citations recorded for this rule type._").unwrap();
        writeln!(out).unwrap();
    }

    // How to fix
    writeln!(out, "### How to fix").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "{}", content.how_to_fix).unwrap();
    writeln!(out).unwrap();

    // PoC scaffold
    render_poc_scaffold(out, finding);

    writeln!(out, "---").unwrap();
    writeln!(out).unwrap();
}

fn render_poc_scaffold(out: &mut String, finding: &ReportFinding) {
    writeln!(out, "### Proof-of-concept scaffold").unwrap();
    writeln!(out).unwrap();

    let bundle = build_evidence_bundle(finding);

    match generate_poc_scaffold(&bundle, &finding.finding_id) {
        Ok(draft) => match validate_poc(&draft, &bundle) {
            Ok(validated) => {
                writeln!(out, "```{}", validated.language).unwrap();
                writeln!(out, "{}", validated.test_code).unwrap();
                writeln!(out, "```").unwrap();
                writeln!(out).unwrap();
                if !validated.assumptions.is_empty() {
                    writeln!(out, "**Assumptions:**").unwrap();
                    for assumption in &validated.assumptions {
                        writeln!(out, "- {}", assumption).unwrap();
                    }
                    writeln!(out).unwrap();
                }
                writeln!(out, "**Status:** {}", validated.status).unwrap();
                writeln!(out, "**Finding ID:** {}", validated.finding_id).unwrap();
                writeln!(out, "**Rule ID:** {}", validated.rule_id).unwrap();
                writeln!(out, "**Language:** {}", validated.language).unwrap();
                writeln!(out, "**Framework:** {}", validated.framework).unwrap();
                writeln!(out).unwrap();
                writeln!(out, "> {}", POC_DISCLAIMER).unwrap();
            }
            Err(_) => {
                writeln!(
                    out,
                    "_PoC scaffold omitted: validation rejected it (off-evidence references or unsupported claim)._"
                )
                .unwrap();
                writeln!(out).unwrap();
                writeln!(out, "> {}", POC_DISCLAIMER).unwrap();
            }
        },
        Err(_) => {
            writeln!(out, "_PoC scaffold not available for this finding type._").unwrap();
        }
    }
    writeln!(out).unwrap();
}

fn build_evidence_bundle(finding: &ReportFinding) -> EvidenceBundle {
    EvidenceBundle {
        id: finding.finding_id.clone(),
        tenant_id: String::new(),
        created_at: String::new(),
        engine_version: EngineVersion {
            semver: env!("CARGO_PKG_VERSION").to_string(),
            git_sha: String::new(),
        },
        input_descriptor: InputDescriptor {
            kind: "source_code".to_string(),
            value: finding.file.clone(),
        },
        provenance: ProvenanceInfo {
            engine: "digger".to_string(),
            source: "deterministic".to_string(),
            deterministic: true,
        },
        findings: vec![Finding {
            finding_id: finding.finding_id.clone(),
            rule_id: finding.rule_id.clone(),
            severity: finding.severity.clone(),
            confidence_label: finding.confidence.clone(),
            locations: vec![Location {
                file: finding.file.clone(),
                line_start: Some(finding.line_start),
                line_end: Some(finding.line_end),
                symbol: Some(finding.component.clone()),
            }],
            evidence_refs: vec![],
            repro_ref: None,
        }],
        artifacts: vec![],
        bundle_hash: String::new(),
        signatures: vec![],
    }
}
