use crate::model::*;
/// Anchor IDL parser — extracts accounts, instructions, constraints from IDL JSON.
///
/// Anchor IDL is generated by `anchor build` and describes the program's interface.
/// This is much more accurate than regex parsing of Rust source code.
use serde::{Deserialize, Serialize};

/// Error type for Anchor IDL parsing operations.
#[derive(Debug, thiserror::Error)]
pub enum ParserError {
    #[error("JSON parse error: {0}")]
    Json(String),

    #[error("IDL structure error: {0}")]
    InvalidIdl(String),

    #[error("IO error: {0}")]
    Io(String),

    #[error("{0}")]
    Other(String),
}

impl From<serde_json::Error> for ParserError {
    fn from(e: serde_json::Error) -> Self {
        ParserError::Json(e.to_string())
    }
}

impl From<std::io::Error> for ParserError {
    fn from(e: std::io::Error) -> Self {
        ParserError::Io(e.to_string())
    }
}

/// Anchor IDL structure (simplified).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnchorIdl {
    pub version: String,
    pub name: String,
    pub instructions: Vec<IdlInstruction>,
    pub accounts: Vec<IdlAccount>,
    #[serde(default)]
    pub types: Vec<IdlType>,
    #[serde(default)]
    pub events: Vec<IdlEvent>,
    #[serde(default)]
    pub errors: Vec<IdlError>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlInstruction {
    pub name: String,
    pub accounts: Vec<IdlAccountMeta>,
    pub args: Vec<IdlArg>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlAccountMeta {
    pub name: String,
    #[serde(alias = "isMut")]
    pub is_mut: bool,
    #[serde(alias = "isSigner")]
    pub is_signer: bool,
    #[serde(default)]
    pub is_optional: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlArg {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlAccount {
    pub name: String,
    #[serde(default)]
    pub discriminator: Vec<u8>,
    #[serde(default)]
    pub fields: Vec<IdlField>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlField {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: serde_json::Value,
    #[serde(default)]
    pub docs: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlType {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlEvent {
    pub name: String,
    #[serde(default)]
    pub fields: Vec<IdlField>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlError {
    pub code: u32,
    pub name: String,
    #[serde(default)]
    pub msg: String,
}

/// Parse an Anchor IDL JSON string into a RawProgram.
pub fn parse_idl(json_str: &str) -> Result<RawProgram, ParserError> {
    let idl: AnchorIdl = serde_json::from_str(json_str)?;

    Ok(extract_from_idl(&idl))
}

fn extract_from_idl(idl: &AnchorIdl) -> RawProgram {
    let mut functions = vec![];
    let mut state = vec![];
    let mut calls = vec![];

    // Extract instructions as functions
    for instruction in &idl.instructions {
        let inputs: Vec<String> = instruction
            .args
            .iter()
            .map(|arg| format!("{}: {}", arg.name, format_ty(&arg.ty)))
            .collect();

        // Determine visibility from account constraints
        let has_signer = instruction.accounts.iter().any(|a| a.is_signer);
        let _has_mut = instruction.accounts.iter().any(|a| a.is_mut);

        let visibility = if has_signer { "public" } else { "unknown" };

        // Build body representation for pattern matching
        let body = format!(
            "accounts: [{}], args: [{}]",
            instruction
                .accounts
                .iter()
                .map(|a| format!("{}(mut={},signer={})", a.name, a.is_mut, a.is_signer))
                .collect::<Vec<_>>()
                .join(", "),
            instruction
                .args
                .iter()
                .map(|a| format!("{}: {}", a.name, format_ty(&a.ty)))
                .collect::<Vec<_>>()
                .join(", ")
        );

        functions.push(RawFunction {
            name: instruction.name.clone(),
            visibility: visibility.into(),
            inputs,
            body,
            ..Default::default()
        });
    }

    // Extract accounts as state
    for account in &idl.accounts {
        let fields: Vec<String> = account
            .fields
            .iter()
            .map(|f| format!("{}: {}", f.name, format_ty(&f.ty)))
            .collect();

        state.push(RawState {
            name: account.name.clone(),
            ty: format!("anchor_account({})", fields.join(", ")),
            ..Default::default()
        });
    }

    // Detect CPI calls from instruction patterns
    for instruction in &idl.instructions {
        // If instruction has "transfer", "swap", "mint" in name — potential CPI
        let name_lower = instruction.name.to_lowercase();
        if name_lower.contains("transfer")
            || name_lower.contains("swap")
            || name_lower.contains("mint")
            || name_lower.contains("burn")
        {
            calls.push(RawCall {
                from: instruction.name.clone(),
                to: "cpi".into(),
                kind: digger_ir::CallKind::CrossProgram,
            });
        }
    }

    RawProgram {
        functions,
        state,
        calls,
        source: String::new(),
        ..Default::default()
    }
}

/// Parse IDL from a file path.
pub fn parse_idl_file(path: &str) -> Result<RawProgram, ParserError> {
    let content = std::fs::read_to_string(path)?;
    parse_idl(&content)
}

/// Try to find and parse an Anchor IDL from a program directory.
pub fn try_parse_idl_from_dir(dir: &str) -> Option<RawProgram> {
    let dir_path = std::path::Path::new(dir);

    // Common IDL locations
    let candidates = [
        dir_path
            .join("target/idl")
            .join(format!("{}.json", dir_path.file_name()?.to_str()?)),
        dir_path.join("idl.json"),
        dir_path
            .join("target/types")
            .join(format!("{}.json", dir_path.file_name()?.to_str()?)),
    ];

    for candidate in &candidates {
        if candidate.exists() {
            if let Ok(program) = parse_idl_file(candidate.to_str()?) {
                return Some(program);
            }
        }
    }

    None
}

fn format_ty(ty: &serde_json::Value) -> String {
    match ty {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Object(map) => {
            if let Some(defined) = map.get("defined") {
                if let Some(name) = defined.as_str() {
                    return name.to_string();
                }
            }
            if let Some(vec) = map.get("vec") {
                return format!("Vec<{}>", format_ty(vec));
            }
            if let Some(option) = map.get("option") {
                return format!("Option<{}>", format_ty(option));
            }
            "unknown".into()
        }
        _ => "unknown".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_string() {
        let result = parse_idl("");
        assert!(result.is_err(), "empty string should fail");
        match result.unwrap_err() {
            ParserError::Json(e) => assert!(!e.is_empty()),
            other => panic!("expected Json error, got {:?}", other),
        }
    }

    #[test]
    fn test_invalid_json() {
        let result = parse_idl("{not valid json}}}");
        assert!(result.is_err(), "invalid JSON should fail");
        match result.unwrap_err() {
            ParserError::Json(e) => assert!(!e.is_empty()),
            other => panic!("expected Json error, got {:?}", other),
        }
    }

    #[test]
    fn test_truncated_json() {
        let result = parse_idl(r#"{"version":"0.1.0","name":"test","instructions":[{"name":"#);
        assert!(result.is_err(), "truncated JSON should fail");
    }

    #[test]
    fn test_partial_solidity_not_json() {
        let result = parse_idl("contract Vault { function deposit() public payable {} }");
        assert!(
            result.is_err(),
            "Solidity source (not JSON) should fail IDL parse"
        );
    }

    #[test]
    fn test_wrong_top_level_type() {
        let result = parse_idl(r#""just a string""#);
        assert!(result.is_err(), "string instead of object should fail");
    }

    #[test]
    fn test_array_instead_of_object() {
        let result = parse_idl("[1, 2, 3]");
        assert!(result.is_err(), "array instead of object should fail");
    }

    #[test]
    fn test_missing_required_fields() {
        let result = parse_idl(r#"{"name":"test"}"#);
        assert!(
            result.is_err(),
            "missing required fields should fail or produce empty"
        );
    }

    #[test]
    fn test_deeply_nested_json() {
        let nested = r#"{"version":"0.1.0","name":"deep","instructions":[],"accounts":[{"name":"A","fields":[{"name":"x","type":{"vec":{"vec":{"vec":{"vec":"u8"}}}}}]}]}"#;
        let result = parse_idl(nested);
        assert!(result.is_ok(), "deeply nested but valid JSON should parse");
    }

    #[test]
    fn test_parse_idl_file_nonexistent() {
        let result = parse_idl_file("/nonexistent/path/to/idl.json");
        assert!(result.is_err(), "nonexistent file should fail");
        match result.unwrap_err() {
            ParserError::Io(e) => assert!(!e.is_empty()),
            other => panic!("expected Io error, got {:?}", other),
        }
    }

    #[test]
    fn test_parse_idl_file_not_json() {
        use std::io::Write;
        let dir = std::env::temp_dir().join("digger_parser_test_not_json");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bad.json");
        {
            let mut f = std::fs::File::create(&path).unwrap();
            f.write_all(b"this is not json").unwrap();
        }
        let result = parse_idl_file(path.to_str().unwrap());
        assert!(result.is_err(), "non-JSON file should fail");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_parser_error_display() {
        let err = ParserError::Json("bad".into());
        let msg = err.to_string();
        assert!(msg.contains("JSON parse error"));
        assert!(msg.contains("bad"));

        let err = ParserError::Io("not found".into());
        let msg = err.to_string();
        assert!(msg.contains("IO error"));

        let err = ParserError::InvalidIdl("missing field".into());
        let msg = err.to_string();
        assert!(msg.contains("IDL structure error"));

        let err = ParserError::Other("misc".into());
        let msg = err.to_string();
        assert_eq!(msg, "misc");
    }

    #[test]
    fn test_json_number_instead_of_object() {
        let result = parse_idl("42");
        assert!(result.is_err(), "number instead of object should fail");
    }

    #[test]
    fn test_null_input() {
        let result = parse_idl("null");
        assert!(result.is_err(), "null should fail");
    }

    #[test]
    fn test_try_parse_idl_from_dir_nonexistent() {
        let result = try_parse_idl_from_dir("/nonexistent/dir");
        assert!(result.is_none(), "nonexistent dir should return None");
    }
}
